summary1=('SELECT '
'hippo_person.id, '
'hippo_person.firstname, '
'hippo_person.surname, '
'hippo_person.othername, '
'hippo_job.title as cadre, '
'hippo_person_contact_work.email, '
'hippo_person_contact_work.telephone, '
'hippo_registration.license_number as License_No, '
'hippo_registration.registration_number as Registration_No, '
'hippo_council.name as Council,'
'hippo_health_facility.name as Health_facility, '
'hippo_trainingprovider.name as Provider, '
'hippo_training.name as Course, '
'hippo_provider_instance.start_date, '
'hippo_provider_instance.end_date, '     
         
'hippo_district.name as County, '
'hippo_health_facility.id_code as id_code, '
'hippo_health_facility.latitude, '
'hippo_health_facility.longitude, '
'hippo_gender.name as Gender '
'FROM '
'hippo_person '
'LEFT JOIN hippo_person_instance on hippo_person.id=hippo_person_instance.parent '
'LEFT JOIN hippo_person_contact_work ON hippo_person_contact_work.parent=hippo_person.id '
'LEFT JOIN hippo_provider_instance on hippo_provider_instance.id=hippo_person_instance.provider_instance '
'LEFT JOIN hippo_providertraining ON hippo_providertraining.id=hippo_provider_instance.providertraining '
'LEFT JOIN hippo_training ON hippo_training.id=hippo_providertraining.training '
'LEFT JOIN hippo_trainingprovider ON hippo_trainingprovider.id=hippo_providertraining.trainingprovider '
'LEFT JOIN hippo_registration ON hippo_registration.parent=hippo_person.id '
'LEFT JOIN hippo_council ON hippo_council.id=hippo_registration.council '
'LEFT JOIN hippo_position ON hippo_position.parent=hippo_person.id '
'LEFT JOIN hippo_job ON hippo_job.id=hippo_position.job '
'LEFT JOIN hippo_health_facility ON hippo_health_facility.id=hippo_position.health_facility '
'LEFT JOIN hippo_district on hippo_district.id = hippo_person.residence '
'LEFT JOIN hippo_demographic on hippo_demographic.parent=hippo_person.id '
'LEFT JOIN hippo_gender on hippo_gender.id=hippo_demographic.gender '
'WHERE '
'hippo_person_instance.attending=1  '
'ORDER BY hippo_provider_instance.start_date ')
